### PR TITLE
Link to tree-sitter objects

### PR DESCRIPTION
**Pull request by JAicewizard**
It took me 2 hours to figure out I needed an extra plugin, and it wasn't builtin to tree-sitter. Hope this links would help anyone in the future

### CODE REVIEW

**Comment by benlubas** [comment]
:skull: I'm sorry about that

**Comment by JAicewizard** [comment]
NP, now im just going to spend another 2 hours to try and get `:MoltenEvaluateOperator<CR>ib` keybinds to work haha

**Comment by benlubas** [comment]
If you'd like, feel free to poke around my config. I can link the relevant stuff:

creating the keybind: https://github.com/benlubas/.dotfiles/blob/31c725c38e7e77b5d19a94a336358c68c67d294c/nvim/lua/plugins/repl.lua#L63

creating the TS capture (as a query): https://github.com/benlubas/.dotfiles/blob/31c725c38e7e77b5d19a94a336358c68c67d294c/nvim/after/queries/markdown/textobjects.scm

using those captures to define a text object: https://github.com/benlubas/.dotfiles/blob/31c725c38e7e77b5d19a94a336358c68c67d294c/nvim/lua/plugins/treesitter.lua#L48

**Comment by JAicewizard** [comment]
It all works when I type it all out myself, just not in a key-bind :) But I'm currently making a stack-overflow question about it and going to bed.

Thanks for the support, really kind :)

**Pull request merged**
