### PR TITLE
Create init.lua

### PR DESCRIPTION
**Pull request by Maegori**
First, thank you for your amazing work here. 

This is a small PR to make sure that [NotebookNavigator.nvim](https://github.com/GCBallesteros/NotebookNavigator.nvim) can interface with molten-nvim. They just want to make sure that molten-nvim is installed, which they check by importing the plugin, which can only be done if there is an init.lua file present.

### CODE REVIEW

**Comment by benlubas** [comment]
Can't they just import the healthcheck? That file will always be there and never change.

```lua
require('molten.health')
```

**Comment by Maegori** [comment]
In principle, they could, but how they currently have set it up (in [this file](https://github.com/GCBallesteros/NotebookNavigator.nvim/blob/main/lua/notebook-navigator/repls.lua)) is a relatively modular way to keep adding REPLs in the future. I think it makes sense, a Neovim plugin is more likely to have an init.lua than a health.lua.

**Comment by benlubas** [comment]
I know that it would be slightly annoying for them to do this. But using "molten.health" as the key for molten would work with their modular system without requiring a (rather pointless) change here, and without requiring a structural change over there.

If this really isn't something that you want to do, I'm not going to die on this hill, I'd just rather not have to have an empty file hanging around.

**Comment by Maegori** [comment]
I can respect that. I can't think of an elegant way to integrate "molten.health" in their current workflow, so I'll open an issue over there to see if they have any ideas or if we can work around it some other way.

**Comment by GCBallesteros** [comment]
Copy pasted from the [issue over at the NotebookNavigator repo](https://github.com/GCBallesteros/NotebookNavigator.nvim/issues/20).

> Importing molten.health is fine. In fact, iron does not have an `init.lua` file either and we are checking for `iron.core` [here](https://github.com/GCBallesteros/NotebookNavigator.nvim/blob/51de12c70d4bddea314b017977c9d69f5f953270/lua/notebook-navigator/init.lua#L35). If you want to work on a PR I will be happy to review it, help and merge once it's ready.

All is fine. This PR can be closed.

**Pull request closed without merging**
